### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by noraj** [mhils/r8#3]
Hi,

Can you provide a docker/docker-compose file for easy, clean, fast deployment?

**Comment by mhils** [comment]
Hi,

I'm not sure if that's particularly useful for r8. I usually deploy it with a bunch of adjacent repos that contain the challenges, just having a simple old-school Python virtualenv and Git repos works great for that. `docker run r8` alone isn't too useful, you really need to be able to configure/develop challenges.

Do you have any convincing use case?

**Comment by noraj** [comment]
> Do you have any convincing use case?

This basically the answer of why using docker.

For:

- More Security
- Easier deployment
- Faster deployment
- More scalable
- Etc.

**Comment by mhils** [comment]
I'm well aware of the general benefits of Docker, I have most of my infrastructure running on that. That being said, it's something I wouldn't personally ever use for r8 and as such don't want to maintain. Sorry!

**Comment by noraj** [comment]
I was saying that for r8 sake. If r8 is only a personal project you can keep it that way, but if you want other people to use it, many people will want a docker.

**Comment by mhils** [comment]
Thanks - I do appreciate the suggestion, but it's nothing I would use or would recommend people to use for this specific piece of software. Lastly, I don't want to maintain it.
